title: "SCASA 41st Annual"
author: "Robert Kabacoff, Ph.D."
description: "&copy; Rob Kabacoff, Ph.D."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false       # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false              # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "Home"}
  - {file: "schedule.md", title: "Schedule"}
  - {file: "slides.md", title: "Slides"}
  - {file: "rcode.md", title: "R Code"}
  - {file: "RiA3e/index.md", title: "Book"}
  - {file: "about.md", title: "Presenter"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:rkabacoff@wesleyan.edu"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
